Failure # 1 (occurred at 2024-05-23_11-21-45)
Traceback (most recent call last):
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\tune\trial_runner.py", line 890, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\tune\ray_trial_executor.py", line 788, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ZeroDivisionError): [36mray::IA2CTrainer.train()[39m (pid=26000, ip=127.0.0.1, repr=IA2CTrainer)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 679, in train
    raise e
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\agents\trainer.py", line 668, in train
    result = Trainable.train(self)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\tune\trainable.py", line 283, in train
    result = self.step()
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\agents\trainer_template.py", line 206, in step
    step_results = next(self.train_exec_impl)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 756, in __next__
    return next(self.built_iterator)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 843, in apply_filter
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 876, in apply_flatten
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 783, in apply_foreach
    for item in it:
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 471, in base_iterator
    yield ray.get(futures, timeout=timeout)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\worker.py", line 1625, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ZeroDivisionError): [36mray::RolloutWorker.par_iter_next()[39m (pid=26000, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.modify_class.<locals>.Class object at 0x000002CE2A9878E0>)
  File "python\ray\_raylet.pyx", line 565, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 569, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 519, in ray._raylet.execute_task.function_executor
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\_private\function_manager.py", line 576, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\iter.py", line 1151, in par_iter_next
    return next(self.local_it)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 378, in gen_rollouts
    yield self.sample()
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\util\tracing\tracing_helper.py", line 451, in _resume_span
    return method(self, *_args, **_kwargs)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\rollout_worker.py", line 753, in sample
    batches = [self.input_reader.next()]
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\sampler.py", line 103, in next
    batches = [self.get_data()]
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\sampler.py", line 233, in get_data
    item = next(self._env_runner)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\sampler.py", line 599, in _env_runner
    _process_observations(
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\evaluation\sampler.py", line 937, in _process_observations
    resetted_obs: Dict[AgentID, EnvObsType] = base_env.try_reset(
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\env\base_env.py", line 450, in try_reset
    obs = self.env_states[env_id].reset()
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\ray\rllib\env\base_env.py", line 528, in reset
    self.last_obs = self.env.reset()
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\marllib\envs\base_env\mpe.py", line 114, in reset
    original_obs = self.env.reset()
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\conversions.py", line 179, in reset
    self.aec_env.reset(seed=seed, options=options)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\supersuit\utils\base_aec_wrapper.py", line 31, in reset
    super().reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\order_enforcing.py", line 118, in reset
    super().reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\base.py", line 38, in reset
    self.env.reset(seed=seed, options=options)
  File "C:\Users\onebean5\anaconda3\envs\marllib\lib\site-packages\supersuit\utils\base_aec_wrapper.py", line 31, in reset
    super().reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\order_enforcing.py", line 118, in reset
    super().reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\base.py", line 38, in reset
    self.env.reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\order_enforcing.py", line 118, in reset
    super().reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\base.py", line 38, in reset
    self.env.reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\wrappers\base.py", line 38, in reset
    self.env.reset(seed=seed, options=options)
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\mpe\_mpe_utils\simple_env.py", line 159, in reset
    self.agent_selection = self._agent_selector.reset()
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\agent_selector.py", line 42, in reset
    return self.next()
  File "C:\Users\onebean5\Desktop\AFRL_MARLlib\MARLLIB\pettingzoo\utils\agent_selector.py", line 47, in next
    self._current_agent = (self._current_agent + 1) % len(self.agent_order)
ZeroDivisionError: integer division or modulo by zero

